export let products = [
  {
    id: 1,
    title: "zapatillas nike",
    price: 30000,
    description: "estas son las mejroes",
    img: "https://res.cloudinary.com/dewk7hnnv/image/upload/v1707328606/cld-sample-5.jpg",
    stock: 12,
    category: "deportivas",
  },
  {
    id: 2,
    title: "zapatillas topper",
    price: 25000,
    description: "comodas y livianas",
    img: "https://res.cloudinary.com/dewk7hnnv/image/upload/v1707328596/samples/shoe.jpg",
    stock: 9,
    category: "deportivas",
  },
  {
    id: 3,
    title: "zapatillas generic",
    price: 49999,
    description: "con camara de aire y ultra comodas",
    img: "https://res.cloudinary.com/dewk7hnnv/image/upload/v1707328574/samples/ecommerce/shoes.png",
    stock: 15,
    category: "deportivas",
  },
  {
    id: 4,
    title: "zapatillasz nike",
    price: 30000,
    description: "estas son las mejroes",
    img: "https://res.cloudinary.com/dewk7hnnv/image/upload/v1707328606/cld-sample-5.jpg",
    stock: 12,
    category: "deportivas",
  },
  {
    id: 5,
    title: "zapatillass nike",
    price: 30000,
    description: "estas son las mejroes",
    img: "https://res.cloudinary.com/dewk7hnnv/image/upload/v1707328606/cld-sample-5.jpg",
    stock: 12,
    category: "deportivas",
  },
  {
    id: 6,
    title: "zapatillasss nike",
    price: 30000,
    description: "estas son las mejroes",
    img: "https://res.cloudinary.com/dewk7hnnv/image/upload/v1707328606/cld-sample-5.jpg",
    stock: 12,
    category: "deportivas",
  },
];
